# Generated by Django 6.0.5 on 2026-06-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_groups_customuser_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("PATIENT", "Patient"),
                    ("DOCTOR", "Doctor"),
                    ("ADMIN", "Admin"),
                    ("RECEPTIONIST", "Receptionist"),
                    ("PHARMACIST", "Pharmacist"),
                ],
                default="PATIENT",
                max_length=20,
            ),
        ),
    ]
