# Generated by Django 6.0.5 on 2026-07-29 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_permission_role_rolepermission_role_permissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="users.role",
            ),
        ),
    ]
