# Generated by Django 6.0.5 on 2026-07-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_role_obj"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="role_obj",
            new_name="role",
        ),
    ]
