# Generated by Django 6.0.5 on 2026-06-06 11:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medical_records", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet(s)"),
                            ("capsule", "Capsule(s)"),
                            ("ml", "Milliliters (ml)"),
                            ("mg", "Milligrams (mg)"),
                            ("g", "Grams (g)"),
                            ("vial", "Vial(s)"),
                            ("bottle", "Bottle(s)"),
                        ],
                        default="tablet",
                        max_length=10,
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Medicine",
                "verbose_name_plural": "Medicines",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dosage", models.CharField(max_length=255)),
                ("frequency", models.CharField(max_length=255)),
                ("duration", models.CharField(max_length=100)),
                (
                    "quantity_prescribed",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Fulfillment"),
                            ("DISPENSED", "Dispensed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("prescribed_at", models.DateTimeField(auto_now_add=True)),
                ("dispensed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="medical_records.medicalrecord",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="pharmacy.medicine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription",
                "verbose_name_plural": "Prescriptions",
                "ordering": ["-prescribed_at"],
            },
        ),
    ]
