# Generated by Django 6.0.5 on 2026-05-23 09:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Practice"),
                            ("CARDIOLOGY", "Cardiology"),
                            ("DERMATOLOGY", "Dermatology"),
                            ("NEUROLOGY", "Neurology"),
                            ("ORTHOPEDICS", "Orthopedics"),
                            ("PEDIATRICS", "Pediatrics"),
                            ("PSYCHIATRY", "Psychiatry"),
                            ("RADIOLOGY", "Radiology"),
                            ("SURGERY", "Surgery"),
                            ("GYNECOLOGY", "Gynecology"),
                        ],
                        default="GENERAL",
                        max_length=50,
                    ),
                ),
                ("license_number", models.CharField(max_length=100, unique=True)),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "consultation_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Profile",
                "verbose_name_plural": "Doctor Profiles",
            },
        ),
        migrations.CreateModel(
            name="DoctorSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "session_duration",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Duration in minutes",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_avaiable", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="doctors.doctorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Schedule",
                "verbose_name_plural": "Doctor Schedules",
                "ordering": ["day_of_week", "start_time"],
                "unique_together": {("doctor", "day_of_week")},
            },
        ),
    ]
