# Generated by Django 6.0.5 on 2026-05-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctorschedule",
            old_name="is_avaiable",
            new_name="is_available",
        ),
    ]
