# Generated by Django 6.0.5 on 2026-09-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_rename_is_avaiable_doctorschedule_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='base_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
