# Generated by Django 6.0.5 on 2026-07-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("doctors", "0002_rename_is_avaiable_doctorschedule_is_available"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CANCELLED"), _negated=True),
                fields=("doctor", "appointment_date", "appointment_time"),
                name="unique_non_cancelled_doctor_appointment_slot",
            ),
        ),
    ]
