# Generated by Django 6.0.5 on 2026-08-05 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0002_alter_appointment_unique_together_and_more"),
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("APPOINTMENT_REMINDER", "Appointment reminder"),
                            ("APPOINTMENT_CANCELLATION", "Appointment cancellation"),
                            ("LOW_STOCK", "Low stock"),
                        ],
                        max_length=40,
                    ),
                ),
                ("deduplication_key", models.CharField(max_length=160, unique=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification_events",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification_events",
                        to="pharmacy.medicine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification event",
                "verbose_name_plural": "Notification events",
                "ordering": ["-created_at"],
            },
        ),
    ]
